# Note:
## kube-ovn
#  - cni-version: 0.3.1
#  - cni-file-name: 01-kube-ovn.conflist
## AWS
#  - cni-version: 1.0.0
#  - cni-file-name: 10-aws.conflist
## Cilium
#  - cni-version: 1.1.0
#  - cni-file-name: 05-cilium.conflist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-daemon-config
data:
  daemon-config.json: |
    {
      "chrootDir": "/hostroot",
      "cniVersion": "0.3.1",
      "logFile": "/var/log/multus.log",
      "logLevel": "error",
      "logToStderr": true,
      "cniConfigDir": "/host/etc/cni/net.d",
      "multusAutoconfigDir": "/host/etc/cni/net.d",
      "multusMasterCNI": "01-kube-ovn.conflist",
      "multusConfigFile": "auto",
      "socketDir": "/host/run/multus/",
      "readinessindicatorfile": "/host/etc/cni/net.d/01-kube-ovn.conflist"
    }
