apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources.yaml

replacements:

  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.ACME_ISSUER_EMAIL
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: create-issuer
        fieldPaths:
          - spec.source.helm.valuesObject.acmeIssuerEmail

  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.AWS_REGION
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: create-issuer
        fieldPaths:
          - spec.source.helm.valuesObject.awsRegion

  - source:
      version: v1
      kind: ConfigMap
      name: kustomize-environment
      fieldPath: data.CERT_MANAGER_ROLE_ARN
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: cert-manager
        fieldPaths:
          - spec.source.helm.valuesObject.serviceAccount.annotations.[eks.amazonaws.com/role-arn]
